version: 2
updates:
  # Enable version updates for Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"

  # Enable version updates for pre-commit hooks
  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
