version: 2
updates:
  # Enable version updates for Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: "/"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: "/"

  # Enable version updates for pre-commit hooks
  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: "/"
