# Copyright (C) 2023 - 2025 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

r""".. _ref_batch_RGP_table:

=========================================================
Using the RGP table real gas model in a batch reactor
=========================================================
This methane liquefaction example shows how to use the Real Gas Properties (RGP) table
generated from the NIST REFPROP database as the real gas model in a batch reactor
simulation.

The RGP table real gas model is a simplified approach to account for
non-ideal gas behavior in simulations involving phase change. It uses
pre-computed tables of thermodynamic and transport properties for a
specific gas species (or a pseudo gas mixture) which can be used to
simulate the behavior of the gas near and below the critical point. Since
the RGP table is generated for a specific gas species, the composition of the gas
must remain the same throughout the simulation. Therefore, no chemical reaction
is allowed when using the RGP table real gas model. The selection of the species
is also limited by the avaiability of the REFPROP data.

The RGP table is generated by the Ansys fluid-properties package with the built-in
REFPROP database. You can download the full Ansys fluid-properties package from
the Ansys GitHub site:
https://github.com/ansys-internal/ansys-fluid-properties

"""

# sphinx_gallery_thumbnail_path = '_static/plot_RGP_methane.png'

##########################
# Import PyChemkin package
# ========================

from pathlib import Path

import matplotlib.pyplot as plt  # plotting
import numpy as np  # number crunching

import ansys.chemkin.core as ck  # Chemkin
from ansys.chemkin.core import Color

# chemkin batch reactor models (transient)
from ansys.chemkin.core.batchreactors.batchreactor import (
    GivenPressureBatchReactorFixedTemperature as Batch,
)
from ansys.chemkin.core.logger import logger

# check working directory
current_dir = str(Path.cwd())
logger.debug("working directory: " + current_dir)
# set verbose mode
ck.set_verbose(True)
# set interactive mode for plotting the results
# interactive = True: display plot
# interactive = False: save plot as a PNG file
global interactive
interactive = True

########################
# Create a chemistry set
# ======================
# Create a gas-phase mechanism input file that contains only one species
# in the RGP table file, methane (CH4). The mechanism file must not contain
# any reaction.

# set mechanism directory (the default Chemkin mechanism data directory)
data_dir = Path(ck.ansys_dir) / "reaction" / "data"

# create a chemistry set object
RGPmech = ck.Chemistry(label="methane_RGP")
#
# create a new mechanism input file in chemkin format
methane_file = Path(current_dir) / "methane_chem.inp"
w = Path.open(methane_file, "w")
# the methane mechanism contains 1 species:
# CH4
# declare elements
w.write("ELEMENT H C END\n")
w.write("SPECIES\n")
w.write("CH4\n")
w.write("END\n")
# no reaction is allowed for RGP table real gas
# The RGP table real gas is a "pseudo mixture" of which
# the composition must remain the same throughtout the simulation
w.write("REACTION\n")
w.write("END\n")
# close the mechnaism file
w.close()
# set mechanism input files
# including the full file path is recommended
RGPmech.chemfile = str(methane_file)
RGPmech.thermfile = str(data_dir / "therm.dat")
# pre-process
_ = RGPmech.preprocess()

# remove the temporary water mechanism file
# Path(methane_file).unlink()

##########################################
# Copy the RGP table to the working folder
# ========================================
# The RGP table data file is generated by the Ansys fluid-properties package
# is located in the examples\data folder. We need to copy the RGP table data file
# to the working folder.

# Find the location of this example py file
try:
    script_dir_obj = Path(__file__).parent.resolve()
except NameError:
    script_dir_obj = Path(current_dir)
script_dir = str(script_dir_obj)
# use the relative path to locate the example mechanism folder
example_mech_data = script_dir_obj / ".." / "data"
print(f"example data = {str(example_mech_data)}")
# the GRP data file is in the example data folder
rgp_source = example_mech_data / "CH4_RGP" / "methane.rgp"
if not rgp_source.exists():
    print(
        Color.RED
        + f">>> RGP data file {str(rgp_source)} does not exist. "
        + "Please check the path. <<<"
        + Color.END
    )
    exit()
rgp_local = Path(current_dir) / "methane.rgp"

# remove existing local RGP data file
if rgp_local.exists():
    rgp_local.unlink()
# copy the RGP data file to the working folder
rgp_local.write_bytes(rgp_source.read_bytes())

###############################
# Set up the mixture conditions
# =============================
# The working fluid "mixture" is pure methane.

methane = ck.Mixture(RGPmech)
# set initial conditions for methane
methane.temperature = 123.0  # 238.0  # K
methane.pressure = 1.0 * ck.P_ATM
methane.x = [("CH4", 1.0)]

######################################################################
# Create the reactor ``tank`` to perform the vapor cooling simulation
# ====================================================================
# Use the ``GivenPressureBatchReactorFixedTemperature()`` method to create
# a constant-pressure batch reactor (with a given temperature profile).
# instantiate the methane liquefaction reactor

LNG = Batch(methane, label="RGP_batch")

############################################
# Set up additional reactor model parameters
# ==========================================
# You must provide reactor parameters, solver controls, and output instructions
# before running the simulations. For a batch reactor, the initial volume and
# simulation end time are required inputs. We use a temperature profile to simulate
# the cooling process. The temperature profile is defined by a set of time and
# temperature data points. The reactor temperature is interpolated at each time step.
# We also need to instruct the reactor model to use the RGP table real gas model and
# provide the path to the RGP data file.

# set up reactor temperature profile
temp_high = methane.temperature
temp_mid = 123.0  # K
temp_final = 111.0  # K, final temperature
temp_prof_time = np.array([0.0, 0.35, 0.5])
temp_prof_data = np.array([temp_high, temp_mid, temp_final])
LNG.set_temperature_profile(x=temp_prof_time, temp=temp_prof_data)

# set reactor parameters
LNG.time = 0.5  # process time in seconds
LNG.volume = 6.0e3  # initial volume in cm3

# set up the RGP table real gas model
LNG.use_rgp_table("methane.rgp")

LNG.set_solver_max_timestep_size(1.0e-5)  # max time step size in seconds
####################
# Run the simulation
# ==================
# Use the ``run()`` method to start the RCM simulation.

# run the CONV reactor model
runstatus = LNG.run()
# check run status
if runstatus != 0:
    # Run failed.
    print(Color.RED + ">>> Run failed. <<<", end=Color.END)
    exit()

# Run succeeded.
print(Color.GREEN + ">>> Run completed. <<<", end=Color.END)
exit()
##########################
# Postprocess the solution
# ========================
# The postprocessing step parses the solution and package the solution values at each
# time point into a mixture. There are two ways to access the solution profiles:
#
# - The raw solution profiles (value as a function of distance) are available
#   for distance, temperature, pressure, volume, and species mass fractions.
#
#  -The mixtures permit the use of all property and rate utilities to extract
#   information such as viscosity, density, and mole fractions.
#
# You can use the ``get_solution_variable_profile()`` method to get
# the raw solution profiles. You can get solution mixtures using either the
# ``get_solution_mixture_at_index()`` method for the solution mixture at
# the given saved location or the ``get_solution_mixture()`` method for
# the solution mixture at the given distance. (In this case, the mixture is
# constructed by interpolation.)
#
# .. note::
#   Use the ``getnumbersolutionpoints()`` method to get the size of
#   the solution profiles before creating the arrays.
#

# postprocess the solutions
LNG.process_solution()
# get the number of solution time points
solutionpoints = LNG.getnumbersolutionpoints()
print(f"Number of solution points = {solutionpoints}.")

# store solution profiles
# simulation time [sec]
sim_time = LNG.get_solution_variable_profile("time")
temp_solution = LNG.get_solution_variable_profile("temperature")
vol_solution = LNG.get_solution_variable_profile("volume")
den_solution = np.zeros(solutionpoints, dtype=np.double)
enthalpy_solution = np.zeros_like(den_solution, dtype=np.double)

for i in range(solutionpoints):
    # get the solution mixture at the given index
    mix_i = LNG.get_solution_mixture_at_index(i)
    # get density [g/cm3]
    den_solution[i] = mix_i.rho
    # get enthalpy [kJ/mole]
    enthalpy_solution[i] = mix_i.hml() * 1.0e-3 / ck.ERGS_PER_JOULE

# clean up
rgp_local.unlink()  # remove the local RGP data file
ck.done()

#################################
# Plot the solution time profiles
# ===============================
# Plot the solution profiles over the entire simulation duration.
# You could observe how the state of the methane varies when
# it is subjected to compression and expansion.

plt.subplots(2, 2, sharex="col", figsize=(12, 6))
plt.suptitle("Solution Time Profiles", fontsize=16)
plt.subplot(221)
plt.plot(sim_time, vol_solution, "b-")
plt.ylabel("Volume [cm3]")
plt.subplot(222)
plt.plot(sim_time, temp_solution, "r-")
plt.ylabel("Temperature [K]")
plt.subplot(223)
plt.plot(sim_time, den_solution, "r-")
plt.xlabel("Time [sec]")
plt.ylabel("Fluid Density [g/cm3]")
plt.subplot(224)
plt.plot(sim_time, enthalpy_solution, "b-")
plt.xlabel("Time [sec]")
plt.ylabel("Enthalpy [kJ/mole]")
# plot results
if interactive:
    plt.show()
else:
    plt.savefig("plot_RGP_methane_batch.png", bbox_inches="tight")
