# Copyright (C) 2023 - 2025 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""Python utilities to post-process Chemkin simulation solutions."""

from __future__ import annotations

import csv
from pathlib import Path
import platform
import subprocess  # nosec B404
from typing import Union

import numpy
import pandas as pd

from ansys.chemkin.core.chemkin_wrapper import get_chemkin_bin_dir
from ansys.chemkin.core.utilities import (
    Color,
    critical_and_exit,
    error_and_exit,
    log_error_message,
    logger,
)


class ChemkinSolutionImporter:
    """Post-process the regular Chemkin simulation solution."""

    """This class make use of Chemkin's post-processor to extract solution data
    from the 'XMLdata.zip' generated by the Chemkin reactor model simulation."""

    def __init__(self):
        """Set up the Chemkin get solution utility for post-processing."""
        # define the chemkin bin folder that holds all the executables
        self.ckbin = get_chemkin_bin_dir()
        print(f"Chemkin bin directory: {self.ckbin}")
        # Chemkin post-processor executable file name
        self.get_soln = ""
        # Chemkin solution transpose file name
        self.soln_transpose = ""
        # Runtime environment setup script for Chemkin
        self.env_file = ""
        # set up the default post-processing utilities
        self._set_ck_postprocessor()
        #
        # check if the get solution executable exists
        self.get_soln_path = str(Path(self.ckbin) / self.get_soln)
        if not Path(self.get_soln_path).exists():
            msg = [
                Color.RED,
                "Chemkin get solution utility not found:",
                self.get_soln_path,
                Color.END,
            ]
            critical_and_exit(Color.SPACE.join(msg))
        # check if the transpose executable exists
        self.soln_transpose_path = str(Path(self.ckbin) / self.soln_transpose)
        if not Path(self.soln_transpose_path).exists():
            msg = [
                Color.RED,
                "Chemkin solution transpose utility not found:",
                self.soln_transpose_path,
                Color.END,
            ]
            critical_and_exit(Color.SPACE.join(msg))
        # command arguments for running the get solution utility can be constructed
        # as needed
        self.get_soln_args: list[str] = []
        # working folder where the XML data file and the optional preference file reside
        # use current folder as the default working directory
        self.work_dir_path = Path.cwd()
        # default XML data file for Chemkin
        self.xml_data_file = "XMLdata.zip"
        self._ckcsv_file = "CKSoln.ckcsv"
        # default preference file for Chemkin solution utility
        self._pref_file = "CKSolnList.txt"
        self._use_pref_file = False
        # default get solution options
        self._get_sensitivity = False
        self._get_rop = False
        self.use_mass_fraction = False
        self._get_everything = False
        self._first_run = True
        # solution data
        self._solution_data: SolutionData | None = None

    def _set_ck_postprocessor(self):
        """Determine the solution utility name for post-processing."""
        """
        Determine the name of the Chemkin get solution utility executable
        for post-processing.
        """
        # check platform
        plat = platform.system()
        if plat == "Windows":
            # Windows
            # set the chemkin runtime environment batch script
            self.env_file = "run_chemkin_env_setup.bat"
            # Chemkin post-processer on windows
            self.get_soln = "GetSolution.exe"
            self.soln_transpose = "CKSolnTranspose.exe"
        elif plat == "Linux":
            # Linux
            # set the chemkin runtime environment for the /bash shell script
            self.env_file = "chemkin_setup.ksh"
            # chemkin post-processer on linux platforms
            self.get_soln = "GetSolution"
            self.soln_transpose = "CKSolnTranspose"
        else:
            msg = [
                Color.RED,
                "unsupported platform",
                str(platform.system()),
                "\n",
                "PyChemkin does not support the current os.",
                Color.END,
            ]
            this_msg = Color.SPACE.join(msg)
            critical_and_exit(this_msg)

    def import_solution(self, soln_file: Union[str, None] = None):
        """Get the solution data using the Chemkin post-processor."""
        """
        Use the Chemkin get solution utility to extract solution data
        from the 'XMLdata.zip' generated by the Chemkin reactor model simulation.
        The GetSolution.exe command-line options:

        GetSolution [-help] [-nosen] [-norop] [-mass] [-all] [-p] [preference_file]
        [XML_zipfile] [abbreviation_file]

        GetSolution generates a comma-delimited text file named CKSoln.ckcsv
        and places it in the working directory.
        """
        # run the get solution utility
        # Define the program and its flags/arguments as separate list items
        command = [self.get_soln_path]
        if self._get_everything:
            command.append("-all")
        else:
            if not self._get_sensitivity:
                command.append("-nosen")
            if not self._get_rop:
                command.append("-norop")
        if self.use_mass_fraction:
            command.append("-mass")
        if self._use_pref_file:
            # the preference file "CKSolnList.txt" will be used if enabled
            command.extend(["-p", self._pref_file])
        if soln_file:
            command.append(soln_file)
        else:
            # use default XML data file if no solution file is provided
            command.append(self.xml_data_file)
        # get solution from the XML data file
        msg = [Color.YELLOW, "Running Chemkin GetSolution utility...", Color.END]
        logger.info(Color.SPACE.join(msg))
        try:
            _ = subprocess.run(  # nosec B603
                command,
                check=True,
                cwd=self.work_dir_path,
                stderr=subprocess.PIPE,
                text=True,
                stdout=subprocess.DEVNULL,
            )
            msg = [
                Color.GREEN,
                "Chemkin ckcsv file generated:",
                self._ckcsv_file,
                Color.END,
            ]
            logger.info(Color.SPACE.join(msg))
        except subprocess.CalledProcessError as e:
            msg = [
                Color.RED,
                "Failed to get solution from Chemkin utility:",
                str(e),
                e.stderr or "",
                Color.END,
            ]
            critical_and_exit(Color.SPACE.join(msg))

    def process_solution_data(self):
        """Import the solution data from the CSV file for further analysis."""
        self.process_ckcsv(self._ckcsv_file)

    def process_ckcsv(self, ckcsv_file: Union[str, None] = None):
        """Process the CSV file containing the solution data."""
        if ckcsv_file:
            csv_file = Path(self.work_dir_path) / ckcsv_file
        else:
            csv_file = Path(self.work_dir_path) / self._ckcsv_file
        if not csv_file.exists():
            msg = [
                Color.RED,
                "Chemkin ckcsv file does not exist:",
                str(csv_file),
                Color.END,
            ]
            critical_and_exit(Color.SPACE.join(msg))
        if self._solution_data is not None:
            msg = [Color.YELLOW, "Clearing previous solutions.", Color.END]
            logger.info(Color.SPACE.join(msg))
            self._solution_data = None
        #
        msg = [Color.YELLOW, "Processing Chemkin ckcsv file:", str(csv_file), Color.END]
        logger.info(Color.SPACE.join(msg))
        self._solution_data = SolutionData(csv_file)
        #
        if self._first_run:
            print(
                "Each solution group represents solutions from\n"
                "1) a reactor/zone/cross section\n"
                "2) a continuation run\n"
                "3) a ROP or sensitivity data block\n"
            )
            self._first_run = False

    def get_help(self):
        """Get help information from the Chemkin solution utility."""
        command = [self.get_soln_path, "-help"]
        try:
            res = subprocess.run(command, check=True, capture_output=True, text=True)  # nosec B603
            print("\n" + Color.YELLOW + "GetSolution help information:\n")
            print(res.stdout)
            print(Color.END)
        except subprocess.CalledProcessError as e:
            msg = [
                Color.RED,
                "Failed to get help from Chemkin solution utility:",
                str(e),
                Color.END,
            ]
            critical_and_exit(Color.SPACE.join(msg))

    def set_working_dir(self, work_dir: str):
        """Set the working directory for the Chemkin solution utility."""
        if not Path(work_dir).exists():
            msg = [
                Color.RED,
                "Working directory does not exist:",
                work_dir,
                Color.END,
            ]
            critical_and_exit(Color.SPACE.join(msg))
        self.work_dir_path = Path(work_dir)

    def generate_preference_file(self, soln_file: Union[str, None] = None):
        """Generate the preference file to customize solution extraction."""
        # run the get solution utility
        if soln_file:
            xml_file = soln_file
        else:
            # use default XML data file if no solution file is provided
            xml_file = self.xml_data_file
        # define the program and its flags/arguments as separate list items
        command = [self.get_soln_path, "-listonly"]

        if (self.work_dir_path / xml_file).exists():
            command.append(xml_file)
        else:
            msg = [
                Color.RED,
                "XML file does not exist:",
                xml_file,
                Color.END,
            ]
            critical_and_exit(Color.SPACE.join(msg))
        # run the command to generate the preference file
        try:
            res = subprocess.run(  # nosec B603
                command,
                check=True,
                capture_output=True,
                cwd=self.work_dir_path,
                text=True,
            )
            if not (self.work_dir_path / self._pref_file).exists():
                msg = [
                    Color.PURPLE,
                    "Preference file not generated:",
                    self._pref_file,
                    "\n",
                    "Return code =",
                    str(res.returncode),
                    Color.END,
                ]
                error_and_exit(Color.SPACE.join(msg))
            else:
                # preference file exists, nothing to do
                msg = [
                    Color.GREEN,
                    "Preference file generated successfully:",
                    self._pref_file,
                    "\n",
                    "Edit the preference file to make user selections.",
                    Color.END,
                ]
                logger.info(Color.SPACE.join(msg))
        except subprocess.CalledProcessError as e:
            msg = [
                Color.RED,
                "Failed to generate preference file:",
                str(e),
                Color.END,
            ]
            critical_and_exit(Color.SPACE.join(msg))

    def set_xml_data_file(self, xml_file: str):
        """Set the XML data file for the Chemkin solution utility."""
        if not (self.work_dir_path / xml_file).exists():
            msg = [
                Color.RED,
                "XML data file does not exist:",
                xml_file,
                Color.END,
            ]
            critical_and_exit(Color.SPACE.join(msg))
        self.xml_data_file = xml_file
        msg = [
            Color.YELLOW,
            "XML data file set to:",
            self.xml_data_file,
            Color.END,
        ]
        logger.info(Color.SPACE.join(msg))

    def use_preference_file(self, pref_file: str):
        """Enable the use of the preference file for the Chemkin solution utility."""
        if not (self.work_dir_path / pref_file).exists():
            self._use_pref_file = False
            msg = [
                Color.RED,
                "Preference file does not exist:",
                pref_file,
                Color.END,
            ]
            logger.critical(Color.SPACE.join(msg))
        else:
            self._pref_file = pref_file
            self._use_pref_file = True
            logger.info(f"Preference file set to: {self._pref_file}")

    def disable_preference_file(self):
        """Disable the use of the preference file for the Chemkin solution utility."""
        self._use_pref_file = False

    def enable_mass_fraction(self):
        """Enable the use of mass fraction for the Chemkin solution utility."""
        self.use_mass_fraction = True

    def disable_mass_fraction(self):
        """Disable the use of mass fraction for the Chemkin solution utility."""
        self.use_mass_fraction = False

    def enable_get_everything(self):
        """Enable the 'get everything' option for the Chemkin solution utility."""
        self._get_everything = True

    def disable_get_everything(self):
        """Disable the 'get everything' option for the Chemkin solution utility."""
        self._get_everything = False

    def enable_sensitivity(self):
        """Enable the sensitivity option for the Chemkin solution utility."""
        self._get_sensitivity = True

    def disable_sensitivity(self):
        """Disable the sensitivity option for the Chemkin solution utility."""
        self._get_sensitivity = False

    def enable_rop(self):
        """Select the rate of progress option for the Chemkin solution utility."""
        self._get_rop = True

    def disable_rop(self):
        """Deselect the rate of progress option for the Chemkin solution utility."""
        self._get_rop = False

    def validate_solution_data(self):
        """Validate the imported solution data."""
        if self._solution_data is None:
            msg = [Color.PURPLE, "No solution data available.", Color.END]
            logger.error(Color.SPACE.join(msg))
            return False
        return True

    def get_solution_groups(self) -> list[str]:
        """Get the list of available solution groups."""
        if not self.validate_solution_data():
            return []
        return list(self._solution_data.get_solution_groups())

    def get_variable_labels(self, solution_group: str) -> list[str]:
        """Get the list of variable labels for a specific solution group."""
        if not self.validate_solution_data():
            return []
        return list(self._solution_data.get_solution_variables(solution_group))

    def get_group_data(self, solution_group: str) -> pd.DataFrame | None:
        """Get the data for a specific solution group."""
        if not self.validate_solution_data():
            return None
        return self._solution_data.get_solution_group_data(solution_group)

    def get_group_object(self, solution_group: str) -> "SolutionGroup" | None:
        """Get the solution group object for a specific solution group."""
        if not self.validate_solution_data():
            return None
        return self._solution_data.get_solution_group_object(solution_group)

    def get_solution_variable_array(
        self, solution_group: str, variable_label: str
    ) -> pd.Series[float] | None:
        """Get the array of data for a specific variable within a solution group."""
        if not self.validate_solution_data():
            return None

        soln_array = self._solution_data.get_solution_array(
            solution_group, variable_label
        )
        return soln_array

    def get_number_of_points(self) -> int:
        """Get the number of solution points in the solution data."""
        return self._solution_data.get_number_of_points()

    def get_number_of_gas_species(self) -> int:
        """Get the number of gas species in the solution data."""
        return self._solution_data.get_number_of_gas_species()

    def get_gas_species_symbols(self) -> list[str]:
        """Get the list of gas species symbols in the solution data."""
        return self._solution_data.get_gas_species_symbols()


class SolutionData:
    """Manage the imported solution data for the Chemkin solution utility."""

    """
    This class manages the imported solution data for the Chemkin solution utility.
    The solution data consists of multiple solution groups, each containing specific
    solution arrays and associated variable labels.
    """

    def __init__(self, ckcsv: str | Path):
        """Initialize the Chemkin solution data utility."""
        # Initialize the solution group utility with the provided CKCSV file.
        self._solutions: dict[str, pd.DataFrame] = {}
        self._current_solution: str | None = None
        self._current_rows: list[list[str | numpy.float64]] = []
        self._skip_data_block = False
        # solution labels
        self._soln_groups: list[str] = []
        # number of gas species in the solution data
        self._number_of_gas_species: int = 0
        # gas species symbols
        self._gas_species_symbols: list[str] = []
        # number of data points in the solution data
        self._number_of_points: int = 0
        # cache of constructed SolutionGroup objects keyed by group name
        self._group_objects: dict[str, SolutionGroup] = {}
        # read the prepared ckcsv solution file
        self.call_reader(ckcsv)
        # get gas species information from the solution data
        self._number_of_gas_species, self._gas_species_symbols = (
            self.get_gas_species_info()
        )
        # get number of solution points from the solution data
        self._number_of_points = self.get_number_of_points()

    def call_reader(self, csv_file: str | Path):
        """Read the solution data from the CSV file."""
        # initialization
        if len(self._solutions) > 0:
            self._solutions.clear()
            self._soln_groups.clear()
            self._group_objects.clear()
        #
        self._current_solution = None
        self._current_rows.clear()
        # read each row from the CSV file and process it accordingly
        with Path(csv_file).open(encoding="utf-8", newline="") as file:
            soln_reader = csv.reader(file)
            for row_number, row in enumerate(soln_reader, start=1):
                if not row:
                    continue
                if len(row) < 2:
                    msg = [
                        Color.RED,
                        "Malformed Chemkin CKCSV row",
                        str(row_number),
                        "must contain at least a variable and unit field.",
                        Color.END,
                    ]
                    critical_and_exit(Color.SPACE.join(msg))
                #
                # Check if the line signals a new metadata block
                if row[0].strip() == "label_2D":
                    # do not process 2D solution data in this reader
                    msg = [Color.YELLOW, "Skipping 2D solution data.", Color.END]
                    logger.info(Color.SPACE.join(msg))
                    # Save the previous block before moving on
                    self.save_current_soln_group()
                    # don't process this block of data
                    self._skip_data_block = True
                elif "rate-of-production" in row[0].strip():
                    # do not process rate-of-production data in this reader
                    msg = [
                        Color.YELLOW,
                        "Skipping rate-of-production data.",
                        Color.END,
                    ]
                    logger.info(Color.SPACE.join(msg))
                    # Save the previous block before moving on
                    self.save_current_soln_group()
                    # don't process this block of data
                    self._skip_data_block = True
                elif row[0].strip() == "label":
                    # Save the previous block before moving on
                    self.save_current_soln_group()
                    if "solution_point_value" in row[1].strip():
                        # do not process single point value data in this reader
                        msg = [
                            Color.YELLOW,
                            "Skipping single point value data.",
                            Color.END,
                        ]
                        logger.info(Color.SPACE.join(msg))
                        # don't process this block of data
                        self._skip_data_block = True
                    else:
                        # Reset the skip flag for the new block
                        self._skip_data_block = False
                        # Set new dictionary key (e.g., 'solution_no_1')
                        self._current_solution = row[1].strip()
                elif not self._skip_data_block:
                    # process the current row only if the block is not skipped
                    try:
                        values = [numpy.float64(value) for value in row[2:]]
                    except ValueError:
                        msg = [
                            Color.RED,
                            "Malformed Chemkin CKCSV row",
                            str(row_number),
                            "contains a nonnumeric solution value.",
                            Color.END,
                        ]
                        critical_and_exit(Color.SPACE.join(msg))
                    self._current_rows.append([row[0].strip(), row[1].strip(), *values])
        # Save the last group after finishing the loop
        self.save_current_soln_group()
        if not self._solutions:
            msg = [
                Color.RED,
                "No supported solution groups found in Chemkin CKCSV file:",
                str(csv_file),
                Color.END,
            ]
            critical_and_exit(Color.SPACE.join(msg))
        #
        msg = [Color.GREEN, "Finished processing Chemkin ckcsv file.", Color.END]
        logger.info(Color.SPACE.join(msg))
        #
        self._soln_groups = list(self._solutions.keys())

    def save_current_soln_group(self):
        """Convert the collected rows into a wide-format DataFrame."""
        if self._skip_data_block:
            return
        if self._current_solution and self._current_rows:
            # Create DataFrame from rows
            df = pd.DataFrame(self._current_rows)
            # Combine first two columns into a MultiIndex (Property, Unit)
            df.set_index([0, 1], inplace=True)
            df.index.names = ["Variable", "Unit"]

            self._solutions[self._current_solution] = df
            self._current_rows = []

    def list_solution_groups(self):
        """List all solution groups for the Chemkin solution utility."""
        groups = self.get_solution_groups()
        if len(groups) == 0:
            msg = [Color.PURPLE, "No solution groups available.", Color.END]
            logger.warning(Color.SPACE.join(msg))
        else:
            print("Solution set/group information:")
            print(f"number of solution groups: {len(groups)}")
            for k, grp in enumerate(groups):
                print(f"  Solution Group {k}: {grp}")
            print("\n")

    def list_solution_variables(self, group_name: str):
        """List all solution variables for the specified solution group."""
        vars = self.get_solution_variables(group_name)
        if len(vars) == 0:
            msg = [
                Color.PURPLE,
                "No solution variables available for group:",
                group_name,
                Color.END,
            ]
            error_and_exit(Color.SPACE.join(msg))
        else:
            print(f"Solution variables in group {group_name}:")
            print(f"number of solution variables: {len(vars)}")
            for var in vars:
                print(f"  {var}")
            print("\n")

    def get_solution_groups(self) -> list[str]:
        """Return a list of all solution group names."""
        return self._soln_groups

    def get_solution_variables(self, group_name: str) -> list[str]:
        """Return a list of all solution variables for the specified group."""
        if not self.validate_group(group_name):
            return []
        return self._get_group_object(group_name).variable_names

    def get_solution_group_data(self, group_name: str) -> pd.DataFrame | None:
        """Return the raw data for the specified solution group."""
        if not self.validate_group(group_name):
            return None
        group_data = self._solutions.get(group_name)
        return group_data

    def get_solution_group_object(self, group_name: str) -> "SolutionGroup" | None:
        """Return the SolutionGroup object for the specified solution group."""
        if not self.validate_group(group_name):
            return None
        return self._get_group_object(group_name)

    def get_solution_array(
        self, group_name: str, var_name: str
    ) -> pd.Series[float] | None:
        """Return the array for the specified variable in the given solution group."""
        if not self.validate_group(group_name):
            return None
        return self._get_group_object(group_name).get_variable_array(var_name)

    def get_number_of_points(self) -> int:
        """Return the number of data points in solution data."""
        group_name = self._soln_groups[0]
        return self._get_group_object(group_name).number_of_points

    def get_gas_species_info(self) -> tuple[int, list[str]]:
        """Return the number of gas species and their symbols in solution data."""
        num = 0
        symbols = []
        for group_name in self._soln_groups:
            group_obj = self._get_group_object(group_name)
            if group_obj.has_gas_species:
                if group_obj.number_of_gas_species > num:
                    num = group_obj.number_of_gas_species
                    symbols = group_obj.gas_species_symbols
        return num, symbols

    def _get_group_object(self, group_name: str) -> "SolutionGroup":
        """Return the cached SolutionGroup for a group, building it if needed."""
        group_obj = self._group_objects.get(group_name)
        if group_obj is None:
            group_obj = SolutionGroup(group_name, self._solutions.get(group_name))
            self._group_objects[group_name] = group_obj
        return group_obj

    def get_number_of_gas_species(self) -> int:
        """Return the number of gas species in the solution data."""
        if len(self._gas_species_symbols) > 0:
            return self._number_of_gas_species
        num, symbols = self.get_gas_species_info()
        self._number_of_gas_species = num
        self._gas_species_symbols = symbols
        return num

    def get_gas_species_symbols(self) -> list[str]:
        """Return the list of gas species symbols in the solution data."""
        if len(self._gas_species_symbols) > 0:
            return self._gas_species_symbols
        num, symbols = self.get_gas_species_info()
        self._number_of_gas_species = num
        self._gas_species_symbols = symbols
        return symbols

    def validate_group(self, group_name: str) -> bool:
        """Validate if the specified solution group exists and has data."""
        this_group = self._solutions.get(group_name, "NA")
        if this_group is None or len(this_group) == 0:
            msg = [
                Color.PURPLE,
                "Solution group does not exist or has no data:",
                group_name,
                Color.END,
            ]
            logger.error(Color.SPACE.join(msg))
            return False
        return True


class SolutionGroup:
    """Class representing a single solution group within the Chemkin solution data."""

    def __init__(self, group_name: str, raw_group_data: "pd.DataFrame"):
        """Initialize a SolutionGroup with the given group name and data."""
        """
        Parameters
        ----------
            group_name: (str)
                The name of the solution group.
            raw_group_data: ("pd.DataFrame")
                A pandas DataFrame representing the data within the group.
                Each row corresponds to a data point.
        """
        self._group_name = group_name
        self._group_data = raw_group_data
        self._number_of_variables = len(raw_group_data)
        self._number_points = 0
        self._has_gas_species = False
        self._solution_type = ""
        suffix = ""
        zone_tag = ""
        burn_tag = ""
        unburn_tag = ""
        if group_name.lower().find("solution_vs_") != -1:
            # line profiles of the averaged values of the solutions
            self._solution_type = "solution"
            self._has_gas_species = False
        elif group_name.lower().find("solution") != -1:
            self._solution_type = "solution"
            self._has_gas_species = True
            zone_tag = "_Zone"
            burn_tag = "_Burn"
            unburn_tag = "_Unburn"
        elif group_name.lower().find("slice") != -1:
            # pseudo 2-D solutions
            self._solution_type = "solution"
            self._has_gas_species = True
            suffix = "_Slice"
        self._variable_name: list[str] = []
        self._variable_index: dict[str, int] = {}
        self._units: list[str] = []
        self._species_map: dict[str, str] = {}
        self._species_symbols: list[str] = []
        self._species_index: dict[str, int] = {}
        self._species_unit: str = "mole"
        self._separator = "_"
        # set up the variable names and units of this solution group
        var_info = list(self._group_data.index)
        for prop in var_info:
            # remove any suffix from the variable name if present
            if len(suffix) > 0:
                end_pos = prop[0].rfind(suffix)
                if end_pos != -1:
                    this_name = prop[0][:end_pos]
                else:
                    this_name = prop[0]
            else:
                this_name = prop[0]
            if self._has_gas_species:
                # extract species symbols from the variable name and
                # build a dictionary to map species symbol to solution variable name
                positions = [
                    index
                    for index, char in enumerate(this_name)
                    if char == self._separator
                ]
                if len(positions) > 0:
                    # extract species symbols and use them as the variable names
                    head = this_name[: positions[0]]
                    # remove the zone tag from the variable name if present
                    b_pos = this_name.rfind(burn_tag)
                    u_pos = this_name.rfind(unburn_tag)
                    if b_pos >= 0 or u_pos >= 0:
                        z_pos = max(b_pos, u_pos)
                    else:
                        z_pos = this_name.rfind(zone_tag)

                    if head == "Mass" and len(positions) > 1:
                        if z_pos == -1:
                            species_symbol = this_name[positions[1] + 1 :]
                        elif z_pos > positions[1]:
                            species_symbol = this_name[positions[1] + 1 : z_pos]
                        else:
                            species_symbol = ""
                        if len(species_symbol) > 0:
                            self._species_unit = "mass"
                            self._add_species(species_symbol, this_name)
                    elif head == "Mole" and len(positions) > 1:
                        if z_pos == -1:
                            species_symbol = this_name[positions[1] + 1 :]
                        elif z_pos > positions[1]:
                            species_symbol = this_name[positions[1] + 1 : z_pos]
                        else:
                            species_symbol = ""
                        if len(species_symbol) > 0:
                            self._species_unit = "mole"
                            self._add_species(species_symbol, this_name)
                    elif head == "Concentration":
                        if z_pos == -1:
                            species_symbol = this_name[positions[0] + 1 :]
                        elif z_pos > positions[0]:
                            species_symbol = this_name[positions[0] + 1 : z_pos]
                        else:
                            species_symbol = ""
                        if len(species_symbol) > 0:
                            self._species_unit = "concentration"
                            self._add_species(species_symbol, this_name)
            #
            self._variable_index[this_name] = len(self._variable_name)
            self._variable_name.append(this_name)
            # extract units
            self._units.append(prop[1])
        # get number of solution points in an array
        if self._number_of_variables > 0:
            row = self._group_data.iloc[0]
            self._number_points = len(row)
        else:
            self._number_points = 0

    @property
    def number_of_variables(self) -> int:
        """Return the number of variables in the solution group."""
        return self._number_of_variables

    @property
    def group_name(self) -> str:
        """Return the name of the solution group."""
        return self._group_name

    @property
    def group_data(self) -> pd.DataFrame:
        """Return the raw data of the solution group."""
        return self._group_data

    @property
    def variable_names(self) -> list[str]:
        """Return the list of variable names in the solution group."""
        return self._variable_name

    @property
    def species_unit(self) -> str:
        """Return the species units of the solution group."""
        return self._species_unit

    @property
    def number_of_points(self) -> int:
        """Return the number of solution points in the solution group."""
        return self._number_points

    @property
    def has_gas_species(self) -> bool:
        """Return True if the solution group has any gas species, False otherwise."""
        return self._has_gas_species

    @property
    def number_of_gas_species(self) -> int:
        """Return the number of gas species in the solution group."""
        if self.has_gas_species:
            return len(self._species_symbols)
        return 0

    @property
    def gas_species_symbols(self) -> list[str]:
        """Return the list of gas species symbols in the solution group."""
        if self.has_gas_species:
            return self._species_symbols
        return []

    def _add_species(self, species_symbol: str, variable_name: str) -> None:
        """Store a gas-species symbol and its associated variable name."""
        if species_symbol not in self._species_map:
            self._species_index[species_symbol] = len(self._species_symbols)
            self._species_symbols.append(species_symbol)
        self._species_map[species_symbol] = variable_name

    def get_variable_index(self, variable_name: str) -> int:
        """Get the index of a variable in the solution group by its name."""
        return self._variable_index.get(variable_name, -1)

    def get_species_index(self, species_symbol: str) -> int:
        """Get the index of a gas species by its symbol."""
        if self.has_gas_species:
            return self._species_index.get(species_symbol, -1)
        return -1

    def get_gas_species_variable_name(self, species_symbol: str) -> str:
        """Get the variable name of a gas species by its symbol."""
        if self.has_gas_species and species_symbol in self._species_map:
            return self._species_map[species_symbol]
        return ""

    def get_gas_species_variable_index(self, species_symbol: str) -> int:
        """Get the variable index of a gas species by its symbol."""
        if self.has_gas_species and species_symbol in self._species_map:
            return self.get_variable_index(self._species_map[species_symbol])
        return -1

    def get_variable_array(self, variable_name: str) -> pd.Series[float]:
        """Get the array of values for a variable by its name."""
        pos_idx = self.get_species_index(variable_name)
        if pos_idx >= 0:
            # name is gas species symbol
            soln_idx = self.get_gas_species_variable_index(variable_name)
        else:
            # name is not a gas species symbol
            soln_idx = self.get_variable_index(variable_name)
        if soln_idx >= 0:
            return self._group_data.iloc[soln_idx]
        msg = [
            Color.PURPLE,
            "Solution variable",
            variable_name,
            "not found in the solution group.",
            Color.END,
        ]
        log_error_message(msg)
        return []

    def get_variable_array_with_tag(
        self, variable_name: str, tag: str
    ) -> pd.Series[float]:
        """Get the array of values for a variable by its name and a tag."""
        pos_idx = self.get_species_index(variable_name)
        if pos_idx >= 0:
            # name is gas species symbol
            if self._species_unit == "mass":
                prefix = "Mass_fraction_"
            elif self._species_unit == "mole":
                prefix = "Mole_fraction_"
            elif self._species_unit == "concentration":
                prefix = "Concentration_"
            else:
                prefix = ""
            suffix = f"_{tag.replace(' ', '_')}"
            this_name = f"{prefix}{variable_name}{suffix}"
        else:
            # name is not a gas species symbol
            this_name = f"{variable_name}_{tag.replace(' ', '_')}"
        soln_idx = self.get_variable_index(this_name)
        if soln_idx >= 0:
            return self._group_data.iloc[soln_idx]
        msg = [
            Color.PURPLE,
            "Solution variable",
            variable_name,
            "not found in the solution group.",
            Color.END,
        ]
        log_error_message(msg)
        return []

    def get_variable_unit(self, variable_name: str) -> str:
        """Get the unit of a variable by its name."""
        pos_idx = self.get_species_index(variable_name)
        if pos_idx >= 0:
            # name is gas species symbol
            if self._species_unit in ["mole", "mass"]:
                this_unit = self._separator.join([self._species_unit, "fraction"])
                return f"({this_unit})"
            else:
                this_unit = self._species_unit
                return f"({this_unit})"
        else:
            # name is not a gas species symbol
            soln_idx = self.get_variable_index(variable_name)
        if soln_idx >= 0:
            return self._units[soln_idx]
        msg = [
            Color.PURPLE,
            "Solution variable",
            variable_name,
            "not found in the solution group.",
            Color.END,
        ]
        log_error_message(msg)
        return ""

    def get_variable_unit_with_tag(self, variable_name: str, tag: str) -> str:
        """Get the unit of a variable by its name."""
        pos_idx = self.get_species_index(variable_name)
        if pos_idx >= 0:
            # name is gas species symbol
            if self._species_unit in ["mole", "mass"]:
                this_unit = self._separator.join([self._species_unit, "fraction"])
                return f"({this_unit})"
            else:
                this_unit = self._species_unit
                return f"({this_unit})"
        else:
            # name is not a gas species symbol
            this_name = f"{variable_name}_{tag.replace(' ', '_')}"
            soln_idx = self.get_variable_index(this_name)
            if soln_idx >= 0:
                return self._units[soln_idx]
            msg = [
                Color.PURPLE,
                "Solution variable",
                variable_name,
                "not found in the solution group.",
                Color.END,
            ]
            log_error_message(msg)
            return ""
